
* libc String Functions Clone

1. *Length*
   * ~strlen~ and ~strnlen~

2. *Copy*
   * ~strcpy~ and ~strncpy~

3. *Concatenate*
   * ~strcat~ and ~strncat~

4. *Compare*
   * ~strcmp~ and ~strncmp~
   * ~strcasecmp~ and ~strncasecmp~

5. *Search*
   * ~strchr~ and ~strrchr~
   * ~strstr, strpbrk, strspn, strcspn~

6. *Token*
   * ~strtok~ and ~strtok_r~

7. *Duplicate*
   * ~strdup~ and ~strndup~

8. *Memory Functions*
   * ~memcpy, memmove, memset, memcmp, memchr, memmem~


* Eval Last Expression for Bash

Ye 2 jagah me chalna chahiye
- bash script file me ~.sh~
- org mode me bash code block me ~src sh~

#+begin_src emacs-lisp
(defun my-lang-context-p (mode lang)
  (or
   (derived-mode-p mode)
   (and (derived-mode-p 'org-mode)
	(org-in-src-block-p)
	(string=
	 (org-element-property :language (org-element-context))
	 lang))))
#+end_src

Now hum kis context me hai ye check kar sakte hai like

#+begin_src emacs-lisp
(my-lang-context-p "fundamental-mode" "emacs-lisp")
#+end_src

Step 1: Simple single line expression

#+begin_src shell
ls
pwd
echo hello world
#+end_src

Ek simple highlight function likhte hai ki hum kya terminal me bhej rahe hai

#+begin_src emacs-lisp
(defun my-highlight (beg end)
  (pulse-momentary-highlight-region beg end))
#+end_src

Now hamara function current idea cursor position se start of line tak bhejna

#+begin_src emacs-lisp
(defun my-eval-last-exp-shell ()
  (interactive)
  (let ((end (point))
	(beg (line-beginning-position)))

    (my-highlight beg end)
    
    (my-vterm-send
     (string-trim
      (buffer-substring-no-properties end beg)))))
#+end_src

#+begin_src emacs-lisp
(global-set-key (kbd "C-M-e") #'my-eval-last-exp-shell)
#+end_src

Step 2: Handling Quotes that span Multiple Lines

#+begin_src shell
echo "hello
world"

echo 'hello
world'
#+end_src

#+begin_src emacs-lisp
(defun my-quotes-balanced-p (expr)
  (let ((single 0)
	(double 0))

    (dotimes (i (length expr))
      (cond
       ((eq (aref expr i) ?')  (setf single (1+ single)))
       ((eq (aref expr i) ?\") (setf double (1+ double)))))

    (and (= (% single 2) 0)
	 (= (% double 2) 0))))
#+end_src

#+begin_src emacs-lisp
(defun my-eval-last-exp-shell ()
  (interactive)
  (let ((end  (point))
	(expr nil)
	(done nil))

    (save-excursion
      (while (and (not done)
		  (re-search-backward "\n" nil t))
	(setf expr (string-trim
		    (buffer-substring-no-properties
		     (1+ (point)) end)))

	(when (my-quotes-balanced-p expr)
	  (my-highlight (1+ (point)) end)
	  (setf done t))))

    expr))
#+end_src


* Terminal Toggle System in Emacs

Hum *vterm* terminal use karenge.
To install

#+begin_src emacs-lisp
(use-package vterm)
#+end_src

Now ab vterm kholne ke liye

#+begin_src emacs-lisp
(vterm)
#+end_src

** Step 1: Show vterm in split-window

Abhi mujhe *vterm* show karna hai split-window me in *below* direction

#+begin_src emacs-lisp
(defun my-vterm-show ()
  (save-window-excursion
    (vterm))

  (let ((win (split-window nil -15 'below)))
    (set-window-buffer win "*vterm*")))
#+end_src

Abhi agar hum ye multiple times run karenge to multiple split-window me terminal khulega.

#+begin_src emacs-lisp
(my-vterm-show)
#+end_src

Toh to solve this,
Hum check karenge ki agar *vterm* pahle se split-window me visible hai ki nahi agar nahi hai tabhi window create karenge.

#+begin_src emacs-lisp
(let ((win (get-buffer-window "*vterm*")))
  (unless win
    (setf win (split-window nil -15 'below))
    (set-window-buffer win "*vterm*")))
#+end_src

Right now hum sirf *below* me split kar rahe hai par mijhe *below* and *right* side dono option chahiye.
Iske liye ek global state variable banate hai

#+begin_src emacs-lisp
(defvar *my-vterm-below* t)
#+end_src

Ab agar *t* to below me split karenge nahi to *right* side me split karenge.

#+begin_src emacs-lisp
(setf win (if my-vterm-below
	      (split-window nil -15 'below)
	    (split-window nil -80 'right)))
#+end_src

Terminal khul raha hai par *point* (cursor) switch nahi kar raha hai
Iske liye function ko argument dedo

#+begin_src emacs-lisp
(defun my-vterm-show (&optional switch)
  ;; ....
  (when switch (select-window win)))
#+end_src

Now ye switch karega

#+begin_src emacs-lisp
(my-vterm-show t)
#+end_src

** Step 2: Decide Terminal Position Based on Window Size

Hum frame ki width nikaal sakte hai emacs me using

#+begin_src emacs-lisp
(frame-width)
#+end_src

Hum apni ek default width set karte hai *right* side me terminal tabhi khule jab minimum width atleast ho frame ki

#+begin_src emacs-lisp
(defconst *my-vterm-min-width-for-right* 180)
#+end_src

Now hum apne ~my-vterm-show~ function me add kar sakte hai

#+begin_src emacs-lisp
(defun my-vterm-show (&optional switch)
  ;; ....

  (unless win
    (when (< (frame-width) *my-vterm-min-width-for-right*)
      (setf *my-vterm-below* t))
    
    ;; ...)))
#+end_src

Now *right* side me tabhi khulega jab frame ki min width *180* ho.

** Step 3: Hide vterm

Mujhe terminal tabhi hide karna jab terminal window focused ho, iske liye hum ek helper function banayenge.
Ye function returns either terminal window *win or nil*.

#+begin_src emacs-lisp
(defun my-vterm-is-focused ()
  (let ((win (get-buffer-window "*vterm*")))
    (if (eq win (selected-window))
	win
      nil)))
#+end_src

Ab hum easily terminal hide kar sakte hai.

#+begin_src emacs-lisp
(defun my-vterm-hide ()
  (let ((win (my-vterm-is-focused)))
    (when win (delete-window win))))
#+end_src

** Step 4: Toggle Terminal Behavior

Ab finally ye main driving function hai jo hum keybinding ke saath use karenge

#+begin_src emacs-lisp
(defun my-vterm-toggle ()
  (interactive)
  (if (my-vterm-is-focused)
      (my-vterm-hide)
    (my-vterm-show t)))
#+end_src

Set it to ~C-`~ keybinding

#+begin_src emacs-lisp
(global-set-key (kbd "C-`") #'my-vterm-toggle)
#+end_src

** Step 5: Move Terminal below <=> right

Idea hai ki pehle *hide* karo fir terminal position update karo aur phir *show* karo.
Par isme ek problem agar terminal *show* hai par focused nahi to kabhi *hide* nahi hoga.

Toh first step *show* karo, isse terminal focused ho jaayega.

#+begin_src emacs-lisp
(defun my-vterm-move ()
  (interactive)
  (my-vterm-show t)

  (setf my-vterm-below
	(not my-vterm-below))

  (my-vterm-hide)
  (my-vterm-show t))
#+end_src

Aur ise ~C-M-`~ keybinding pe set kar dete hai.

#+begin_src emacs-lisp
(global-set-key (kbd "C-M-`") #'my-vterm-move)
#+end_src

** Step 6: Send Command to Terminal

#+begin_src emacs-lisp
(defun my-vterm-send (command)
  (my-vterm-show)
  (with-current-buffer "*vterm*"
    (goto-char (point-max))
    (vterm-send-string command t)
    (vterm-send-return)))
#+end_src

~(vterm-send-string command t)~
Isme *t* paste ki tarah bhejta hai nahi to char-by-char bhejega
Isse python me indentation problem aa sakti hai.

Now ab hum commands run kar sakte hai

#+begin_src emacs-lisp
(my-vterm-send "ls")
(my-vterm-send "echo hello world")
#+end_src




* Theme Switcher in Emacs

~custom-enabled-themes~ Emacs ka built-in variable hai jo currently enabled themes ki list rakhta hai.

#+begin_src emacs-lisp
custom-enabled-themes
#+end_src

Toh general idea ye hai ki ye saari purani themes ko disable karo.

Ek time par multiple themes enabled ho sakti hain. Isliye nayi theme load karne se pehle purani themes disable kar dete hain taaki colors mix na hon.

#+begin_src emacs-lisp
(mapc #'disable-theme custom-enabled-themes)
#+end_src

Aur uske baad apni theme load karo.

#+begin_src emacs-lisp
(load-theme 'tango-dark t)
#+end_src

** Step 1: Install Theme Package

#+begin_src emacs-lisp
(use-package doom-themes)
#+end_src

Hum apni kuch favorite themes se selection karenge.

#+begin_src emacs-lisp
(defvar *my-themes*
  '(doom-material-dark
    doom-1337
    doom-acario-dark
    doom-ir-black))
#+end_src

Hamara current theme index.

#+begin_src emacs-lisp
(defvar *my-theme-index* 0)
#+end_src

** Step 2: Load Theme

~my-load-theme~ function *index* lega aur us index ki theme load karega.

#+begin_src emacs-lisp
(defun my-load-theme (index)
  (let* ((len   (length *my-themes*))
	 (idx   (mod index len))
	 (theme (nth idx *my-themes*)))
    (mapc #'disable-theme custom-enabled-themes)
    (load-theme theme t)
    (setf *my-theme-index* idx)
    (message "Theme Loaded: %s" theme)))
#+end_src

Ye hamara main driving function hai jo cycle karega through all our themes.

#+begin_src emacs-lisp
(defun my-cycle-themes ()
  (interactive)
  (my-load-theme (1+ *my-theme-index*)))
#+end_src

Set it to a keybinding.

#+begin_src emacs-lisp
(global-set-key (kbd "<f5>") #'my-cycle-themes)
#+end_src

Mujhe jo emacs ki default white theme hai wo bhi chahiye to ~*my-themes*~ variable me hum ek *default* naam se theme add kar dete hai.

#+begin_src emacs-lisp
(defvar *my-themes*
  '(default
    ....))
#+end_src

fir *my-load-theme* function me.

#+begin_src emacs-lisp
(unless (eq theme 'default)
  (load-theme theme t))
#+end_src

*load-theme* tabhi call karo agar *default* theme na set ho.

** Step 3: Save Theme on Exit

Is File me hum apni theme state save karenge.

#+begin_src emacs-lisp
(defvar *my-theme-state-file* "~/.emacs.d/theme-state.el")
#+end_src

- Jab Emacs exit hota hai, tab ~kill-emacs-hook~ trigger hota hai.
- ~kill-emacs-hook~ ek hook variable hai jo functions ki list store karta hai.
- Emacs exit hone par is list ke sabhi functions automatically execute kiye jaate hain.
- Hum apna function bhi isi hook me add karenge.

#+begin_src emacs-lisp
(add-hook 'kill-emacs-hook
	  (lambda ()
	    (with-temp-file *my-theme-state-file*
	      (insert (format "(setf *my-theme-index* %d)"
			      *my-theme-index*)))))
#+end_src

Is File me humne emacs-lisp ka expression store kar diya hai example like:

#+begin_src emacs-lisp
(setf *my-theme-index* 2)
#+end_src

** Step 4: Loading Theme on Startup

Hum check karenge ki agar ~*my-theme-state-file*~ exists karti hai to use load kar do.

#+begin_src emacs-lisp
(when (file-exists-p *my-theme-state-file*)
  (load-file *my-theme-state-file*))
#+end_src

Isko run karke hamara ~*my-theme-index*~ variable update ho jaayega.

Finally,

#+begin_src emacs-lisp
(my-load-theme *my-theme-index*)
#+end_src
